version: '3.5'

services:
  vector_service:
    container_name: vector-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
    volumes:
      - ./data:/app/data
    ports:
      - "8002:8002"
    restart: unless-stopped

networks:
  default:
    name: vector-service-network 