FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/app

# Create directory for Chroma database
RUN mkdir -p /app/data/chroma_db

ENV CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db

EXPOSE 8002

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"] 